imports_granularity = "Crate"
reorder_imports = true
# quicker manual lookup
group_imports = "StdExternalCrate"
# why use an attribute if a normal doc comment would suffice?
normalize_doc_attributes = true
# why not?
wrap_comments = true

format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

# reference
# https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#reorder_imports

# use nightly in cmd line
# cargo +nightly fmt 

#### fmt on save
#"[rust]": {
#    "editor.defaultFormatter": "rust-lang.rust-analyzer",
#    "editor.formatOnSave": true,
#},

#### with unstable feature
# "rust-analyzer.rustfmt.extraArgs": [
#    "+nightly"
#]    
